name: Run Cucumber Tests with ChromeDriver on Windows 11

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Usamos Windows para ejecutar el flujo de trabajo en Windows 11

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install Google Chrome
        run: |
          choco install googlechrome --version=131.0.6778.265 -y

      - name: Install ChromeDriver
        run: |
          choco install chromedriver --version=131.0.6778.265 -y

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: mvn clean install -f PruebasCucumber/pom.xml
